name: auto-merge

on: [pull_request,workflow_dispatch]

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          github-token: ${{ github.TOKEN }}
